"""Render the two demo Slack payloads as a realistic Slack-message HTML preview,
then screenshot it (see README). Generates demo/slack_preview.html.
"""
from __future__ import annotations

import json
import os

from .config import load_config
from .models import Alert, STATUS_EARLY, STATUS_CONFIRMED

OUT = os.path.join(os.path.dirname(__file__), "..", "demo", "out")


def _esc(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _payload_to_html(payload: dict, channel_label: str) -> str:
    blocks = payload.get("blocks", [])
    html = []
    for blk in blocks:
        btype = blk.get("type")
        if btype == "header":
            html.append(f'<div class="header">{_esc(blk["text"]["text"])}</div>')
        elif btype == "section":
            html.append(f'<div class="section">{_esc(blk["text"]["text"])}</div>')
        elif btype == "context":
            parts = [e.get("text", "") for e in blk.get("elements", [])]
            html.append(f'<div class="context">{_esc("   ·   ".join(parts))}</div>')
        elif btype == "actions":
            btns = []
            for b in blk.get("elements", []):
                btns.append(f'<span class="btn">{_esc(b["text"]["text"])} ↗</span>')
            html.append(f'<div class="actions">{"".join(btns)}</div>')
    return "\n".join(html)


def build_preview():
    cfg = load_config()
    # reload demo payloads from disk (generated by demo.py)
    early = json.load(open(os.path.join(OUT, "early_signal.json")))
    confirmed = json.load(open(os.path.join(OUT, "confirmed.json")))

    def card(payload, label, color):
        return f"""
        <div class="msg">
          <div class="avatar">{color}</div>
          <div class="body">
            <div class="appbar">{_esc(payload.get('username','YC Launch Monitor'))}  <span class="app">APP</span>  <span class="time">just now</span></div>
            <div class="chan">{_esc(label)}</div>
            {_payload_to_html(payload, label)}
          </div>
        </div>"""

    html = f"""<!doctype html><html><head><meta charset="utf-8">
<style>
  body {{ background:#f0f2f5; font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif; padding:40px; }}
  .msg {{ display:flex; gap:12px; background:#fff; border-radius:8px; padding:16px 20px; margin:0 auto 20px; max-width:720px;
          box-shadow:0 1px 2px rgba(0,0,0,.08); }}
  .avatar {{ width:40px; height:40px; border-radius:5px; color:#fff; display:flex; align-items:center; justify-content:center; font-weight:700; flex-shrink:0; }}
  .body {{ flex:1; min-width:0; }}
  .appbar {{ font-weight:700; font-size:15px; color:#1d1c1d; }}
  .app {{ background:#ecebf1; color:#1d1c1d; border-radius:3px; font-size:10px; font-weight:700; padding:1px 5px; vertical-align:middle; }}
  .time {{ color:#616061; font-weight:400; font-size:12px; }}
  .chan {{ color:#1264a3; font-size:12px; font-weight:700; margin:2px 0 6px; }}
  .header {{ font-size:17px; font-weight:700; margin:6px 0 4px; }}
  .section {{ font-size:14px; color:#1d1c1d; margin:4px 0; white-space:pre-wrap; }}
  .context {{ font-size:12px; color:#616061; margin:6px 0; }}
  .actions {{ margin:8px 0 2px; }}
  .btn {{ display:inline-block; border:1px solid rgba(29,28,29,.3); border-radius:4px; padding:4px 10px; font-size:13px; color:#1d1c1d; margin-right:6px; }}
  h2 {{ color:#1d1c1d; max-width:720px; margin:30px auto 12px; }}
</style></head><body>
<h2>Example 1 — Early YC founder signal (detected before official listing)</h2>
{card(early, "#yc-launch-monitor", "⚡")}
<h2>Example 2 — Official Speedrun company (confirmed)</h2>
{card(confirmed, "#yc-launch-monitor", "✅")}
</body></html>"""

    path = os.path.join(os.path.dirname(OUT), "slack_preview.html")
    with open(path, "w") as fh:
        fh.write(html)
    print(f"[preview] wrote {path}")
    return path


if __name__ == "__main__":
    build_preview()
